### ISSUE TITLE
insert_ext() row_span & col_span appear swapped

### ISSUE THREAD

**Issue by TomDeRybel** [fltk-rs/fltk-grid#1]
First off, thank you for all your work on fltk-rs. I highly appreciate your efforts to make this venerable (and solid) toolkit more accessible.

I've been working on a little tool and encountered two issues:
- The row_span and col_span fields appear to be swapped for insert_ext() (L137, L138).
- I can't get the grid to resize when the GUI resizes. (This is likely me being clueless, any clues are very much appreciated.)

To illustrate the issues, please find a short test program attached.
[fltk_test.zip](https://github.com/fltk-rs/fltk-grid/files/8464728/fltk_test.zip)

**Comment by MoAlyousef** [comment]
Thank you for your kind words. 

1- The behavior is correct, the terms might be confusing. row_span is the span of the passed row value, which is counted in columns. While col_span is the span of the passed column value, which is counted in rows. I'll improve the docs there.

2- Since the default resizing behavior can vary depending on the application, it's better to define it using the resize_callback of the Grid's parent. In your attached program, I've removed EqCtlStage::grd and EqCtlStage::resize() and added the following towards the end of EqCtlStage::new():
```rust
        grp.resize_callback(
            move |_, x, y, w, h| {
                grd.resize(x, y, w, h);
            }
        );

        Self { grp }
```

**Comment by TomDeRybel** [comment]
Thank you for your quick and detailed reply!

1) Thank you for the clear explanation and proposed doc improvements.

2) I've done as you proposed and the resizing now works as intended. Calling the resize of the grid in the group resize callback is something I hadn't though of (though saw mentioned in the FLTK docs on layout). Seeing and understanding being quite different things, unfortunately.

Have a lovely evening,
Tom

**Comment by jkl1337** [comment]
I'm not seeing how row span/column span as implemented make much sense. Say you have a 4 row x 6 column grid, and want to put an item in column 5 (starting from 0) and covering rows 0 and 1 (what I think most table implementations would call a row span of 2, certainly that's how it works in HTML for instance).
The insert call for this is quite counterintuitively: insert(..., row: 0, col: 5..7). This really makes no sense to me, why is the effective height span of 2 in the column argument ?- the number 7 makes no senses, the 2 rows are not an offset from 5! The math in insert_ext really should swap the calculation of width and height.

**Comment by MoAlyousef** [comment]
I agree that the overload taking ranges should be swapped, or even just removed.
